{% set name = "langchain-chroma" %}
{% set version = "0.2.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/langchain_chroma-{{ version }}.tar.gz
  sha256: b63e9df8c3fbb316313c232214b7bc8b696a505039a6f7adf29b992a74cc4b2e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pdm-backend
    - pip
  run:
    - python >={{ python_min }},<3.13
    - langchain-core >=0.3.70
    - chromadb >=1.0.9
    - numpy >=1.26.0
    - fastapi <1,>=0.95.2
  run_constrained:
    - fastapi >=0.95.2,<1

test:
  imports:
    - langchain_chroma
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/langchain-ai/langchain
  summary: An integration package connecting Chroma and LangChain
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
