{% set name = "langchain-chroma" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/langchain_chroma-{{ version }}.tar.gz
  sha256: 67754c50d0adb6fa2ebf07ea48026e025c9bffe2ae329e769d4c6e2b6398eaa8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<3.13
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.8.1,<3.13
    - langchain-core >=0.1.40,<0.3
    - chromadb >=0.4.0,<0.6.0
    - numpy >=1.0.0,<2.0.0
    - fastapi <1,>=0.95.2
  run_constrained:
    - fastapi >=0.95.2,<1

test:
  imports:
    - langchain_chroma
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/langchain-ai/langchain
  summary: An integration package connecting Chroma and LangChain
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
